"""Generated views of the intent tree: the routing map and the machine index.

Both files are derived data. They are regenerated by ``intent map`` and checked by
``intent validate``; nobody edits them by hand.
"""

from __future__ import annotations

import json

from intent.model import INDEX_FILENAME, MAP_FILENAME, Tree

GENERATED_BANNER = "<!-- generated by `intent map` — do not edit by hand -->"


def _contract_summary(tree: Tree, node_id: str) -> str:
    node = tree.nodes[node_id]
    if not node.contracts:
        return "—"
    return "; ".join(contract.text for contract in node.contracts)


def render_map(tree: Tree) -> str:
    """Render ``MAP.md``: one line per node, small enough to always be readable."""
    lines = [
        "# Intent map",
        "",
        GENERATED_BANNER,
        "",
        "| Id | Path | Title | Contracts | Code |",
        "|----|------|-------|-----------|------|",
    ]
    for node in tree.sorted_nodes():
        path = "/".join(tree.path_of(node.id))
        code = ", ".join(f"`{item}`" for item in node.code_paths) or "—"
        contracts = _contract_summary(tree, node.id).replace("|", "\\|")
        title = node.title.replace("|", "\\|")
        lines.append(f"| `{node.id}` | `{path}` | {title} | {contracts} | {code} |")
    lines.append("")
    lines.append("## Tree")
    lines.append("")
    lines.append("```mermaid")
    lines.append("graph TD")
    for node in tree.sorted_nodes():
        label = f"{node.id}<br/>{node.title}".replace('"', "'")
        lines.append(f'    {node.id}["{label}"]')
    for node in tree.sorted_nodes():
        if node.parent:
            lines.append(f"    {node.parent} --> {node.id}")
    for node in tree.sorted_nodes():
        for target in node.uses:
            lines.append(f"    {node.id} -.uses.-> {target}")
        for target in node.talks_to:
            lines.append(f"    {node.id} -.talks_to.-> {target}")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def build_index(tree: Tree) -> dict[str, object]:
    """Build the machine index, including the reverse code-path map."""
    nodes: dict[str, object] = {}
    reverse: list[dict[str, str]] = []
    for node in tree.sorted_nodes():
        path = tree.path_of(node.id)
        nodes[node.id] = {
            "id": node.id,
            "slug": node.slug,
            "title": node.title,
            "status": node.status,
            "parent": node.parent,
            "path": "/".join(path),
            "depth": len(path) - 1,
            "children": [child.id for child in tree.children_of(node.id)],
            "uses": node.uses,
            "talks_to": node.talks_to,
            "code_paths": node.code_paths,
            "test_paths": node.test_paths,
            "contracts": [
                {
                    "id": contract.id,
                    "text": contract.text,
                    "enforced_by": contract.enforced_by,
                    "reason": contract.reason,
                }
                for contract in node.contracts
            ],
            "open_questions": node.open_questions,
            "file": str(node.source.relative_to(tree.root_dir)) if node.source else None,
        }
        for code_path in node.code_paths:
            reverse.append({"code_path": code_path, "node": node.id, "depth": str(len(path) - 1)})

    reverse.sort(key=lambda entry: (entry["code_path"], -int(entry["depth"])))
    return {
        "schema_version": 1,
        "nodes": nodes,
        "reverse_code_map": reverse,
    }


def render_index(tree: Tree) -> str:
    return json.dumps(build_index(tree), indent=2, ensure_ascii=False) + "\n"


def write_generated(tree: Tree) -> list[str]:
    """Write both generated files; return the list of files that changed."""
    changed: list[str] = []
    for filename, content in (
        (MAP_FILENAME, render_map(tree)),
        (INDEX_FILENAME, render_index(tree)),
    ):
        target = tree.intent_dir / filename
        previous = target.read_text(encoding="utf-8") if target.exists() else None
        if previous != content:
            target.write_text(content, encoding="utf-8")
            changed.append(str(target.relative_to(tree.root_dir)))
    return changed


def generated_is_current(tree: Tree) -> list[str]:
    """Return the generated files whose content is stale."""
    stale: list[str] = []
    for filename, content in (
        (MAP_FILENAME, render_map(tree)),
        (INDEX_FILENAME, render_index(tree)),
    ):
        target = tree.intent_dir / filename
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            stale.append(filename)
    return stale
